server:
  port: 9098
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port:  6379
    password:  root
    database: 4
  redisson:
    codec: org.redisson.codec.JsonJacksonCodec
    threads:  4
    netty:
      threads:  4
    single-server-config:
      address:  "redis://localhost:6379"
      password:  root
      database:  0
