liteflow:
  rule-source-ext-data-map:
    url: jdbc:mysql://localhost:3306/demo
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    applicationName: demo
    #是否开启SQL日志
    sqlLogEnabled: true
    #是否开启SQL数据轮询自动刷新机制 默认不开启
    pollingEnabled: true
    pollingIntervalSeconds: 60
    pollingStartSeconds: 60
    #以下是chain表的配置，这个一定得有
    chainTableName: chain
    chainApplicationNameField: application_name
    chainNameField: chain_name
    elDataField: el_data
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
    scriptTableName: script
    scriptApplicationNameField: application_name
    scriptIdField: script_id
    scriptNameField: script_name
    scriptDataField: script_data
    scriptTypeField: script_type
    scriptLanguageField: script_language
spring:
  #  # Redis 连接参数 （RedisProperties）
  redis:
    host: 127.0.0.1
    database: 5
    password: root
    port: 6379
  redisson:
    codec: org.redisson.codec.JsonJacksonCodec
    threads: 4
    netty:
      threads: 4
    single-server-config:
      address: "redis://localhost:6379"
      password: root
      database: 5

