canal:
  server: 127.0.0.1:11111
  destination: example
spring:
  redis:
    host: 47.98.114.98
    password: root
    port: 6379
    database: 3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/demo
      username: root
      password: root
