spring:
  redis:
    host: 47.98.114.98
    password: root
    port: 6379
    database: 3
  datasource:
    druid:
      driverClassName: ${jdbc.driver}
      password: ${jdbc.password}
      url: ${jdbc.url}
      username: ${jdbc.username}
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: liteflow
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/pqiot_v3?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
  username: root
  password: root
server:
  port: 9865
knife4j:
  basic:
    enable: false
    password: 123456
    username: admin
  enable: true
  openapi:
    description: API文档
    group:
      demo:
        api-rule: package
        api-rule-resources:
          - com.iot
        group-name: iot
    license: MIT
    title: 在线文档
    version: v1.0.0